#
# ================================================
# * Discuz! Ucenter API for JAVA
# ================================================
# UC comunication settings
#  
# 
#uc server url
UC_API =
#uc ip address
UC_IP =

#key
UC_KEY =

#appid
UC_APPID =

#connect mode: default value is ""
UC_CONNECT =


APPID =100400

SECRET =SbYymvfZ8UjEmShxRAB0b1Dtaa0uGjDOOJa/f0Mbuo4=

ilabUrl =http://202.205.145.156:8017



#APPID =104013
#
#SECRET =+6shHLLwAaG85QN4oy5DEBT4GgNpWZjV4qVQuoHLz/I=
#
#ilabUrl =http://www.ilab-x.com