# stand GTAP global model - Linux paths for local dev
SRDIR =/home/debian/Public/javaproject/gvcproject/nzdx-data/SRDIR/
CHN-GEO =/home/debian/Public/javaproject/gvcproject/nzdx-data/CHN-GEO/
CHN-AUS =/home/debian/Public/javaproject/gvcproject/nzdx-data/CHN-AUS/
CHN-UKR =/home/debian/Public/javaproject/gvcproject/nzdx-data/CHN-UKR/
RCEP =/home/debian/Public/javaproject/gvcproject/nzdx-data/RCEP/
CHN-WLD-RICE =/home/debian/Public/javaproject/gvcproject/nzdx-data/CHN-WLD-RICE/
CHN-WLD-FTZ =/home/debian/Public/javaproject/gvcproject/nzdx-data/CHN-WLD-FTZ/
SELF_DEFIN =/home/debian/Public/javaproject/gvcproject/nzdx-data/SELF_DEFIN/
DocFile =/home/debian/Public/javaproject/gvcproject/nzdx-data/DocFile/
